# Generated by Django 4.0.4 on 2022-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='show_room',
            name='Showroom_count',
            field=models.IntegerField(default=0),
        ),
    ]
