# Generated by Django 4.0.4 on 2022-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0003_alter_carmodels_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='Modelyear',
            field=models.IntegerField(verbose_name='_year'),
        ),
    ]
