# Generated by Django 4.0.4 on 2022-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0006_alter_carlist_modelyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='Modelyear',
            field=models.CharField(max_length=4),
        ),
    ]
