# Generated by Django 4.0.4 on 2022-04-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0009_alter_carlist_modelyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='Modelyear',
        ),
    ]
